#!/bin/bash
set -e

# parse arguments
POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    --image-source)
    IMAGE_SOURCE="$2"
    shift # past argument
    ;;
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
esac
done


BASENAME_IS=`basename $IMAGE_SOURCE`

# run predictions
DOCKER_RUN="docker run --entrypoint entrypoints/entrypoint.predict.cpu.sh -v "$IMAGE_SOURCE":/src/$BASENAME_IS nima-cpu /src/$BASENAME_IS"

eval $DOCKER_RUN
